### ISSUE TITLE
broadCastToUnit fails due to dodgy string comparison

### ISSUE THREAD

**Issue by rokel** [suegy/IA-AgentScape-Rover#4]
At line [521 of the RoverService](https://github.com/suegy/IA-AgentScape-Rover/blob/master/rover/rover.service/src/main/java/rover/RoverService.java#L521), the `==` operator is used to compare the remoteUnit id, causing message passing to fail. The `.equals` operator should be used instead for string comparisons.

Fix - replace line 521 with this:
`if (ri.getTeam() == rover.getTeam() && remoteUnit.equals(rover.getClientKey()))`

**Comment by suegy** [comment]
Fixed in latest version. 
Thanks for spotting!

**Comment by rokel** [comment]
Cheers, no worries
